services:
  library-api:
    build:
      context: ./Library.API
      dockerfile: Dockerfile
    environment:
      - Api__ReportingServiceUrl=library-reporting
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - library-network
    ports:
      - "80:80"
    depends_on:
      - library-reporting
    develop:
      watch:
        - path: ./Library.API/
          action: rebuild

  library-reporting:
    build:
      context: ./Library.ReportingService
      dockerfile: Dockerfile
    environment:
      - Reporting__LibraryDbConnStr=Server=library-db;Database=LibraryDB;Integrated security=false;User=sa;Password=Your(5tr0ng)Password;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:50051
    networks:
      - library-network
    depends_on:
      - library-db
    develop:
      watch:
        - path: ./Library.ReportingService/
          action: rebuild

  library-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Your(5tr0ng)Password
      - ACCEPT_EULA=Y
    networks:
      - library-network
    ports:
      - "1433:1433"

networks:
  library-network:
    driver: bridge
